/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/XW6ZwhDp5iz
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"

export function versionCard() {
  return (
    <div className="min-h-screen bg-gray-50">
      <header className="flex items-center justify-between p-4 bg-white shadow-md md:px-8">
        <div className="flex items-center space-x-4">
          <LogInIcon className="w-6 h-6" />
          <span className="text-xl font-bold">Quickit</span>
        </div>
        <nav className="flex items-center space-x-4 md:space-x-6">
          <Button variant="ghost">Dashboard</Button>
          <Button variant="ghost">AI Assistant</Button>
          <Button variant="ghost">News & Updates</Button>
          <Button variant="ghost">Subscription</Button>
        </nav>
        <div className="flex items-center space-x-4">
          <BellIcon className="w-6 h-6" />
          <Avatar>
            <AvatarImage src="/placeholder-user.jpg" />
            <AvatarFallback>U</AvatarFallback>
          </Avatar>
        </div>
      </header>
      <main className="p-8 md:p-12">
        <section className="mb-8">
          <div className="relative w-full h-48 bg-gradient-to-r from-purple-400 via-pink-500 to-red-500 rounded-lg md:h-64">
            <div className="absolute inset-0 flex items-center justify-center text-white">
              <h1 className="text-4xl font-bold dark:text-black md:text-5xl">What's new?</h1>
            </div>
          </div>
          <div className="flex flex-col items-start justify-between mt-4 md:flex-row md:items-center">
            <p className="text-gray-600 mb-4 md:mb-0">
              A changelog of the latest <span className="font-semibold">Quickit</span> feature releases, product updates
              and important bug fixes.
            </p>
            <Button variant="outline">Changelog in 2023</Button>
          </div>
        </section>
        <section className="space-y-8 md:space-y-12">
          <div className="flex flex-col items-start space-x-4 md:flex-row">
            <div className="w-full text-right mb-4 md:w-1/4 md:mb-0">
              <p className="text-gray-500">Nov 25, 2023</p>
            </div>
            <div className="relative w-full md:w-3/4">
              <div className="absolute left-0 w-0.5 h-full bg-gray-200 md:h-[calc(100%+2rem)] md:top-[-1rem]" />
              <Card className="relative ml-4 overflow-hidden bg-white shadow-md">
                <div className="absolute inset-0 w-full h-full bg-gradient-to-r from-blue-400 via-purple-500 to-pink-500 opacity-20" />
                <CardHeader>
                  <CardTitle>Version 2.1</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-2">
                    <h3 className="text-lg font-semibold">Improvements & Changes</h3>
                    <ul className="list-disc list-inside">
                      <li>Added a new page with a changelog</li>
                    </ul>
                    <h3 className="text-lg font-semibold">Bugfixes</h3>
                    <ul className="list-disc list-inside">
                      <li>Fixed AI operation in some cases</li>
                      <li>Fixed technical problems that led to failures</li>
                    </ul>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
          <div className="flex flex-col items-start space-x-4 md:flex-row">
            <div className="w-full text-right mb-4 md:w-1/4 md:mb-0">
              <p className="text-gray-500">Aug 6, 2023</p>
            </div>
            <div className="relative w-full md:w-3/4">
              <div className="absolute left-0 w-0.5 h-full bg-gray-200 md:h-[calc(100%+2rem)] md:top-[-1rem]" />
              <Card className="relative ml-4 overflow-hidden bg-white shadow-md">
                <div className="absolute inset-0 w-full h-full bg-gradient-to-r from-purple-500 via-pink-500 to-red-500 opacity-20" />
                <CardHeader>
                  <CardTitle>Version 2.0</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-2">
                    <h3 className="text-lg font-semibold">Improvements & Changes</h3>
                    <ul className="list-disc list-inside">
                      <li>Added the ability to flexibly configure subscription management</li>
                    </ul>
                    <h3 className="text-lg font-semibold">Bugfixes</h3>
                    <ul className="list-disc list-inside">
                      <li>Reduced data loading and updating time</li>
                    </ul>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
//@ts-ignore
function BellIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9" />
      <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0" />
    </svg>
  )
}

//@ts-ignore
function LogInIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4" />
      <polyline points="10 17 15 12 10 7" />
      <line x1="15" x2="3" y1="12" y2="12" />
    </svg>
  )
}
export default versionCard;